version: '3'

services:
  web:
    build:
        context: .
        dockerfile: Dockerfile-Frontend
    labels:
    - traefik.enable=true
    - traefik.port=8000
    - traefik.frontend.rule=Host:web.r4.ie
    - traefik.tags=${TRAEFIK_PUBLIC_TAG:-traefik-public}
    - traefik.docker.network=traefik-public
    # Traefik service that listens to HTTP
    - traefik.redirectorservice.frontend.entryPoints=http
    - traefik.redirectorservice.frontend.redirect.entryPoint=https
    # Traefik service that listens to HTTPS
    - traefik.webservice.frontend.entryPoints=https
    command: gunicorn root.wsgi:application --workers 2 --bind :8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
    - traefik-public

  ionic:
    build:
        context: .
        dockerfile: Dockerfile-Frontend
    labels:
      - traefik.frontend.rule=Host:web2.r4.ie
      - traefik.enable=true
      - traefik.port=80
      - traefik.tags=${TRAEFIK_PUBLIC_TAG:-traefik-public}
      - traefik.docker.network=traefik-public
      # Traefik service that listens to HTTP
      - traefik.redirectorservice.frontend.entryPoints=http
      - traefik.redirectorservice.frontend.redirect.entryPoint=https
      # Traefik service that listens to HTTPS
      - traefik.webservice.frontend.entryPoints=https
    volumes:
     - .:/code
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true

networks:
  traefik-public:
    external: true
