# Generated by Django 2.2.6 on 2019-11-03 23:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20191029_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OBJECTID', models.CharField(max_length=100)),
                ('Planning_Authority', models.CharField(max_length=100)),
                ('Tier', models.CharField(max_length=10)),
                ('Planning_Reference', models.CharField(max_length=100)),
                ('Planning_Permission_Units_Perm', models.CharField(max_length=10)),
                ('Units_Completed_to_Date', models.CharField(max_length=10)),
                ('Units_Under_Construction', models.CharField(max_length=10)),
                ('Activity_On_Site', models.CharField(max_length=2)),
                ('Units_Permitted_But_Not_Commenc', models.CharField(max_length=10)),
                ('Planning_Search_URL', models.CharField(max_length=1000)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'ordering': ('OBJECTID',),
            },
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
