# Generated by Django 2.2.6 on 2019-11-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20191103_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='Planning_Permission_Units_Perm',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
