# Generated by Django 2.2.6 on 2019-11-05 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20191103_2320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planning',
            options={},
        ),
    ]
