# Generated by Django 2.2.6 on 2019-12-12 23:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20191105_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectoralDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OBJECTID', models.CharField(max_length=100)),
                ('LE_ID', models.CharField(max_length=100)),
                ('LE_ENGLISH', models.CharField(max_length=10)),
                ('LE_GAEILGE', models.CharField(max_length=100)),
                ('COUNTY', models.CharField(blank=True, max_length=10, null=True)),
                ('CONTAE', models.CharField(max_length=10)),
                ('PROVINCE', models.CharField(max_length=10)),
                ('CENTROID_X', models.CharField(max_length=2)),
                ('CENTROID_Y', models.CharField(max_length=10)),
                ('GUID', models.CharField(max_length=1000)),
                ('ObjectID_1', models.CharField(max_length=1000)),
                ('Shape_Area', models.CharField(max_length=1000)),
                ('Shape_Length', models.CharField(max_length=1000)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.DeleteModel(
            name='Planning',
        ),
    ]
