version: '3'

services:
  web:
    build: .
    labels:
    - traefik.enable=true
    - traefik.port=8000
    - traefik.frontend.rule=Host:web.r4.ie
    - traefik.tags=${TRAEFIK_PUBLIC_TAG:-traefik-public}
    - traefik.docker.network=traefik-public
    # Traefik service that listens to HTTP
    - traefik.redirectorservice.frontend.entryPoints=http
    - traefik.redirectorservice.frontend.redirect.entryPoint=https
    # Traefik service that listens to HTTPS
    - traefik.webservice.frontend.entryPoints=https
    - traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:*
    command: gunicorn root.wsgi:application --workers 2 --bind :8000
    networks:
    - traefik-public

networks:
  traefik-public:
    external: true
