version: '3.3'

services:
  backend:
    image: crimsonprince/webmapping
    labels:
    - "traefik.enable=true"
    - "traefik.http.middlewares.webmapping-https.redirectscheme.scheme=https"
    - "traefik.http.routers.webmapping-http.entrypoints=web"
    - "traefik.http.routers.webmapping-http.rule=Host(`api.r4.ie`)"
    - "traefik.http.routers.webmapping-http.middlewares=webmapping-https@docker"
    - "traefik.http.routers.webmapping.entrypoints=web-secure"
    - "traefik.http.routers.webmapping.rule=Host(`api.r4.ie`)"
    - "traefik.http.routers.webmapping.tls=true"
    - "traefik.http.routers.webmapping.tls.certresolver=default"
    - traefik.frontend.headers.customResponseHeaders=Access-Control-Allow-Origin:*
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    networks:
    - traefik-public

networks:
  traefik-public:
    external: true
