name: Deploy
on: [push]
jobs:
  frontend:
    name: DeployFrontend
    runs-on: ubuntu-latest
    steps:
    - name: Executes SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        command_timeout: 2m
        script: |
          cd WebMappingAssignment/frontend
          git pull
          docker-compose down
          docker-compose up --build -d

  backend:
    name: DeployBackend
    runs-on: ubuntu-latest
    steps:
    - name: Executes SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        command_timeout: 2m
        script: |
          cd WebMappingAssignment/root
          git pull
          docker-compose down
          docker-compose up --build -d
